# Generated by Django 4.0.4 on 2022-06-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('ex_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('activity', models.CharField(blank=True, max_length=1000)),
                ('aerobic', models.CharField(blank=True, max_length=1)),
                ('met', models.IntegerField(blank=True, default=0)),
                ('level', models.IntegerField(blank=True, default=0)),
                ('ex_name', models.CharField(blank=True, max_length=1000)),
                ('target_category', models.CharField(blank=True, max_length=1000)),
                ('muscle', models.CharField(blank=True, max_length=1000)),
                ('equipment', models.CharField(blank=True, max_length=1000)),
                ('imgUrl', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('f_NO', models.AutoField(primary_key=True, serialize=False)),
                ('f_id', models.CharField(blank=True, max_length=100)),
                ('f_DB', models.CharField(blank=True, max_length=100)),
                ('f_name', models.CharField(blank=True, max_length=100)),
                ('f_por', models.IntegerField(blank=True, default=0)),
                ('f_carb', models.FloatField(blank=True, default=0)),
                ('f_protein', models.FloatField(blank=True, default=0)),
                ('f_fat', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
