# Generated by Django 4.0.4 on 2022-06-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('f_NO', models.AutoField(primary_key=True, serialize=False)),
                ('f_id', models.CharField(blank=True, max_length=100)),
                ('f_DB', models.CharField(blank=True, max_length=100)),
                ('f_name', models.CharField(blank=True, max_length=100)),
                ('f_por', models.IntegerField(blank=True, default=0)),
                ('f_carb', models.FloatField(blank=True, default=0)),
                ('f_protein', models.FloatField(blank=True, default=0)),
                ('f_fat', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
