# Generated by Django 4.0.4 on 2022-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPage', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='imgUrl',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
