# Generated by Django 4.0.4 on 2022-06-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPage', '0003_alter_exercise_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='target_category',
            field=models.CharField(blank=True, choices=[('Abs', '코어'), ('Arms', '팔'), ('Back', '등'), ('Chest', '가슴'), ('Legs', '하체'), ('Shoulders', '어깨')], max_length=1000),
        ),
    ]
