# Generated by Django 4.0.4 on 2022-06-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPage', '0004_alter_exercise_target_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='target_category',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
