# Generated by Django 4.0.4 on 2022-06-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealBoard',
            fields=[
                ('b_No', models.AutoField(primary_key=True, serialize=False)),
                ('m_Pro', models.CharField(blank=True, max_length=100)),
                ('b_Title', models.CharField(max_length=1000)),
                ('b_Content', models.TextField(blank=True)),
                ('b_Group', models.IntegerField(default=0)),
                ('b_Step', models.IntegerField(default=1)),
                ('b_Indent', models.IntegerField(default=0)),
                ('b_Hit', models.IntegerField(default=0)),
                ('b_File', models.ImageField(blank=True, upload_to='')),
                ('b_Createdate', models.DateTimeField(auto_now_add=True)),
                ('b_Modidate', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Member.members')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseBoard',
            fields=[
                ('b_No', models.AutoField(primary_key=True, serialize=False)),
                ('m_Pro', models.CharField(blank=True, max_length=100)),
                ('b_Title', models.CharField(max_length=1000)),
                ('b_Content', models.TextField(blank=True)),
                ('b_Group', models.IntegerField(default=0)),
                ('b_Step', models.IntegerField(default=1)),
                ('b_Indent', models.IntegerField(default=0)),
                ('b_Hit', models.IntegerField(default=0)),
                ('b_File', models.ImageField(blank=True, upload_to='')),
                ('b_Createdate', models.DateTimeField(auto_now_add=True)),
                ('b_Modidate', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Member.members')),
            ],
        ),
    ]
