# Generated by Django 4.0.4 on 2022-06-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseboard',
            name='b_File',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
