# Generated by Django 4.0.4 on 2022-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_alter_exerciseboard_b_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealboard',
            name='b_File',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
