# Generated by Django 4.0.5 on 2022-06-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0006_alter_members_user_target'),
        ('Board', '0003_alter_mealboard_b_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseboard',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.members'),
        ),
        migrations.AlterField(
            model_name='mealboard',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.members'),
        ),
    ]
