# Generated by Django 4.0.4 on 2022-06-13 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminPage', '0001_initial'),
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyexercise',
            fields=[
                ('ex_No', models.AutoField(primary_key=True, serialize=False)),
                ('ex_time', models.IntegerField(blank=True, default=0)),
                ('burned_kcal', models.IntegerField(blank=True, default=0)),
                ('goal_kcal', models.IntegerField(blank=True, default=1000)),
                ('content', models.TextField(blank=True)),
                ('createdate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 13, 13, 59, 5, 81798))),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminPage.exercise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Member.members')),
            ],
        ),
    ]
