# Generated by Django 4.0.4 on 2022-06-16 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DailyCheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexercise',
            name='createdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
