# Generated by Django 4.0.4 on 2022-06-13 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_alter_members_createdate_alter_members_modidate'),
        ('AdminPage', '0001_initial'),
        ('DailyCheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_meal_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 13, 8, 54, 51, 337612))),
                ('d_meal_time', models.CharField(choices=[('B', '아침'), ('L', '점심'), ('D', '저녁'), ('S', '간식')], max_length=10, null=True)),
                ('d_food_name', models.CharField(blank=True, max_length=100)),
                ('d_por', models.IntegerField(blank=True, default=0)),
                ('d_carb', models.FloatField(blank=True, default=0)),
                ('d_protein', models.FloatField(blank=True, default=0)),
                ('d_fat', models.FloatField(blank=True, default=0)),
                ('d_kcal', models.IntegerField(blank=True, default=0)),
                ('d_food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AdminPage.food')),
                ('d_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Member.members')),
            ],
        ),
    ]
