# Generated by Django 4.0.4 on 2022-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyCheck', '0002_alter_dailyexercise_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='d_img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
