# Generated by Django 4.0.5 on 2022-06-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0006_alter_members_user_target'),
        ('DailyCheck', '0003_alter_dailymeal_d_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeal',
            name='d_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Member.members'),
        ),
    ]
