from pyexpat import model
from django.db import models
from PIL import Image

class Members(models.Model):
    user_id = models.CharField(max_length=20,primary_key=True)
    user_pw = models.CharField(max_length=100)
    user_name = models.CharField(max_length=100)
    pro_Choice=((0,'비전문가'),(1,'전문가'))
    pro = models.IntegerField(default=0,choices=pro_Choice)
    birth = models.DateField(blank=True)
    gender_Choice=(('M','남자'),('F','여자'),('U','선택 안함'))
    gender = models.CharField(max_length=10,choices=gender_Choice,blank=True)
    phone = models.CharField(max_length=13,blank=True)
    email = models.CharField(max_length=1000,blank=True)
    zipcode = models.CharField(max_length=6,blank=True)
    addressd1=models.CharField(max_length=1000,blank=True)
    addressd2=models.CharField(max_length=1000,blank=True)
    user_purpose = models.CharField(max_length=1000,blank=True)
    service_Choice=(('meal','식단'),('loseweight','체중감량'),('excersize','운동'))
    service = models.CharField(max_length=1000,choices=service_Choice,blank=True)
    vegan_Choice=(('vegan','비건채식'),('lacto','락토채식'),('ovo','오보채식'),('lactoovo','락토오보채식'),('pollo','폴로채식'),('pesco','페스코채식'),('flexitarian','플렉시테리안'),('notvegan','해당사항없음'))
    vegan = models.CharField(max_length=100,choices=vegan_Choice,blank=True)
    allergic_food = models.CharField(max_length=1000,blank=True)
    goal_wieght = models.IntegerField(default=55,blank=True)
    goal_bodyfat = models.IntegerField(default=25,blank=True)
    createdate=models.DateTimeField(auto_now_add=True)
    modidate=models.DateTimeField(auto_now=True)
    
class Dailydata(models.Model):
    user = models.ForeignKey(Members,on_delete=models.CASCADE)
    height = models.IntegerField(blank=True)
    cur_weight = models.IntegerField(blank=True)
    cur_bmi=models.IntegerField(blank=True)
    cur_bodyfat = models.IntegerField(blank=True)
    cur_neck = models.IntegerField(blank=True)
    cur_waist = models.IntegerField(blank=True)
    cur_hip = models.IntegerField(blank=True)
    day_img = models.ImageField(blank=True)
    ex_level = models.CharField(max_length=100,blank=True)
    week_ex = models.IntegerField(default=0,blank=True)
    day_ex = models.IntegerField(default=0,blank=True)
    focus_ex = models.CharField(max_length=1000,blank=True)
    add_date=models.DateTimeField(auto_now_add=True)
    