# Generated by Django 4.0.4 on 2022-06-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
