# Generated by Django 4.0.4 on 2022-06-15 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(default=0, max_length=100)),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('pro', models.CharField(choices=[('notadvance', '비전문가'), ('advance', '전문가')], max_length=100, null=True)),
                ('birth', models.DateField(default=datetime.date.today, null=True)),
                ('gender', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=10, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('email', models.CharField(max_length=1000, null=True)),
                ('zipcode', models.CharField(max_length=6, null=True)),
                ('addressd1', models.CharField(max_length=1000, null=True)),
                ('addressd2', models.CharField(max_length=1000, null=True)),
                ('addressd3', models.CharField(max_length=1000, null=True)),
                ('user_purpose', models.CharField(choices=[('weightlose', '체중감소'), ('maintain', '체중유지'), ('weightgain', '체중증가')], max_length=1000, null=True)),
                ('user_target', models.CharField(choices=[('abs', '복부'), ('shoulders', '어깨'), ('arms', '팔'), ('back', '등'), ('chest', '가슴'), ('legs', '하체'), ('all', '전신')], max_length=1000, null=True)),
                ('service', models.CharField(choices=[('meal', '식단형'), ('balance', '균형형'), ('exercise', '운동형')], max_length=1000, null=True)),
                ('vegan', models.CharField(choices=[('vegan', '비건채식'), ('lacto', '락토채식'), ('ovo', '오보채식'), ('lactoovo', '락토오보채식'), ('pollo', '폴로채식'), ('pesco', '페스코채식'), ('flexitarian', '플렉시테리안'), ('notvegan', '해당사항없음')], max_length=100, null=True)),
                ('allergic_food', models.CharField(max_length=1000, null=True)),
                ('goal_weight', models.IntegerField(default=55, null=True)),
                ('goal_bodyfat', models.IntegerField(default=25, null=True)),
                ('goal_period', models.IntegerField(default=30, null=True)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('modidate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dailydata',
            fields=[
                ('day_no', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.IntegerField(null=True)),
                ('cur_weight', models.IntegerField(null=True)),
                ('cur_bmi', models.IntegerField(null=True)),
                ('cur_bodyfat', models.IntegerField(null=True)),
                ('cur_neck', models.IntegerField(null=True)),
                ('cur_waist', models.IntegerField(null=True)),
                ('cur_hip', models.IntegerField(null=True)),
                ('day_img', models.ImageField(null=True, upload_to='')),
                ('ex_level', models.CharField(choices=[('2', '저강도 운동'), ('3', '중강도 운동'), ('6', '고강도 운동')], max_length=100, null=True)),
                ('week_ex', models.IntegerField(default=0, null=True)),
                ('day_ex', models.IntegerField(default=0, null=True)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('goal_eat_kcal', models.IntegerField(default=1000, null=True)),
                ('goal_burn_kcal', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Member.members')),
            ],
        ),
    ]
