# Generated by Django 4.0.4 on 2022-06-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='user_pw',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
