# Generated by Django 4.0.4 on 2022-06-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_dailydata_day_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='day_img',
            field=models.ImageField(blank=True, default='../static/img/mem01.png', upload_to=''),
        ),
    ]
