# Generated by Django 4.0.4 on 2022-06-09 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_members_user_pw'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='addressd1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='addressd2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='addressd3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='allergic_food',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='birth',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 9, 15, 18, 59, 822931)),
        ),
        migrations.AddField(
            model_name='members',
            name='email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='goal_bodyfat',
            field=models.IntegerField(default=25, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='goal_period',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='goal_weight',
            field=models.IntegerField(default=55, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='modidate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 9, 15, 18, 59, 822931)),
        ),
        migrations.AddField(
            model_name='members',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='pro',
            field=models.CharField(choices=[('notadvance', '비전문가'), ('advance', '전문가')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='service',
            field=models.CharField(choices=[('meal', '식단형'), ('balance', '균형형'), ('exercise', '운동형')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='user_purpose',
            field=models.CharField(choices=[('weightlose', '체중감소'), ('maintain', '체중유지'), ('weightgain', '체중증가')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='user_target',
            field=models.CharField(choices=[('abs', '복부'), ('shoulders', '어깨'), ('arms', '팔'), ('back', '등'), ('chest', '가슴'), ('legs', '하체'), ('all', '전신')], max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='vegan',
            field=models.CharField(choices=[('vegan', '비건채식'), ('lacto', '락토채식'), ('ovo', '오보채식'), ('lactoovo', '락토오보채식'), ('pollo', '폴로채식'), ('pesco', '페스코채식'), ('flexitarian', '플렉시테리안'), ('notvegan', '해당사항없음')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='zipcode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
