# Generated by Django 4.0.4 on 2022-06-09 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_members_addressd1_members_addressd2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='createdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 9, 15, 34, 30, 820327)),
        ),
        migrations.AlterField(
            model_name='members',
            name='modidate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 9, 15, 34, 30, 820327)),
        ),
        migrations.CreateModel(
            name='Dailydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True)),
                ('cur_weight', models.IntegerField(blank=True)),
                ('cur_bmi', models.IntegerField(blank=True)),
                ('cur_bodyfat', models.IntegerField(blank=True)),
                ('cur_neck', models.IntegerField(blank=True)),
                ('cur_waist', models.IntegerField(blank=True)),
                ('cur_hip', models.IntegerField(blank=True)),
                ('day_img', models.ImageField(blank=True, upload_to='')),
                ('ex_level', models.CharField(blank=True, choices=[('2', '저강도 운동'), ('3', '중강도 운동'), ('6', '고강도 운동')], max_length=100)),
                ('week_ex', models.IntegerField(blank=True, default=0)),
                ('day_ex', models.IntegerField(blank=True, default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.members')),
            ],
        ),
    ]
