# Generated by Django 4.0.4 on 2022-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_alter_dailydata_day_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='day_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
