# Generated by Django 4.0.5 on 2022-06-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0006_alter_members_user_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='cur_bmi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='cur_bodyfat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='cur_hip',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='cur_neck',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='cur_waist',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='cur_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='height',
            field=models.FloatField(null=True),
        ),
    ]
