# Generated by Django 4.0.4 on 2022-06-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0007_alter_dailydata_cur_bmi_alter_dailydata_cur_bodyfat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_target',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
